import 'package:flutter/material.dart';

const KBackGroundColor = Color(0xFFFFFFFF);
const KTextFeildSingUpColor = Color(0xFF3593FF);
const Kmainthemecolor = Color(0xFFF899C0);
const KColor = Color(0xFF063E7E);
const KFont = "Montserrat";
const KProductCollection='Products';
const KProductName='ProductName';
const KProductPrice='ProductPrice';
const KProductDescription='ProductDescription';
const KProductLocation='ProductLocation';
const KProductCategory='ProductCategory';
const KProductQuantity='ProductQuantity';
const KProductID='ProductID';
const KStream='Stream';
const KStreamStoreName = 'StreamStoreName';
const KStreamtime = 'Streamtime';
const KStreamUID = 'StreamUID';
const KUser = 'user';
const KUserFullname = 'userFullname';
const KUserUsername = 'userUsername';
const KUseremail = 'userEmail';
const KUserbirthdate = 'userBirthdate';
const KUserUID = 'userUID';